### ISSUE TITLE
[Suggest] Add "back to top" button for document page.

### ISSUE THREAD

**Issue by woorui** [taosdata/official_website#1]
强烈建议给文档加一个回到顶部的按钮，因为常常需要回看目录，不太方便

**Comment by changxiaoqiang** [comment]
多谢反馈，目前正在在处理新文档模块的开发和内容整理，近期就会上线。
可以先预览下：https://docs.taosdata.com/intro

**Comment by woorui** [comment]
嗯嗯，谢谢回复，我是从 https://www.taosdata.com/ 进来，在 title 的位置点击`文档`，跳转的是 https://www.taosdata.com/docs/cn/v2.0/index

这个地方文档没有这个button

**Comment by changxiaoqiang** [comment]
> 

目前是个预览版本，部分文档结构和内容还在做细微的调整，并未将入口正式开放，所以官网上暂时没有链接到此处。
